version: '3.8'

services:
  app:
    build: ./docker
    ports: ["5000:5000"]
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports: ["11434:11434"]
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
